services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./routes:/app/routes
      - ./islands:/app/islands
      - ./components:/app/components
      - ./utils:/app/utils
      - ./internalization:/app/internalization
      - ./deno.json:/app/deno.json
    environment:
      - PORT=8000
      - ARTICLES_SERVER_URL=http://articles-server:8081
      - GO_SERVER_URL=http://articles-server:8081
      - DENO_ENV=development
    restart: unless-stopped
    command: run -A --watch=routes/,islands/,components/,utils/,internalization/ dev.ts
    
  articles-server:
    build:
      context: ./go-cluster-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./static/articles:/app/static/articles
    environment:
      - STATIC_DIR=/app/static/articles
      - PORT=8081
    restart: unless-stopped

volumes:
  article-data: 