services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - article-data:/app/static/articles
    environment:
      - PORT=8000
      - ARTICLES_SERVER_URL=http://articles-server:8081
      - GO_SERVER_URL=http://articles-server:8081
      - DENO_ENV=production
    restart: unless-stopped
    depends_on:
      - articles-server
    command: run -A --watch=routes/,islands/,components/,utils/,internalization/ dev.ts
    
  articles-server:
    build:
      context: ./go-cluster-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - article-data:/app/static/articles
    environment:
      - STATIC_DIR=/app/static/articles
      - PORT=8081
    restart: unless-stopped

volumes:
  article-data: 